# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/schlexander/Code/PhysicsCmulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/schlexander/Code/PhysicsCmulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/schlexander/Code/PhysicsCmulation/CMakeFiles /home/schlexander/Code/PhysicsCmulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/schlexander/Code/PhysicsCmulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhysXCmulation.exe

# Build rule for target.
PhysXCmulation.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysXCmulation.exe
.PHONY : PhysXCmulation.exe

# fast build rule for target.
PhysXCmulation.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/build
.PHONY : PhysXCmulation.exe/fast

PhysicsCmulation/physics/src/ForceObject.o: PhysicsCmulation/physics/src/ForceObject.cpp.o

.PHONY : PhysicsCmulation/physics/src/ForceObject.o

# target to build an object file
PhysicsCmulation/physics/src/ForceObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/ForceObject.cpp.o
.PHONY : PhysicsCmulation/physics/src/ForceObject.cpp.o

PhysicsCmulation/physics/src/ForceObject.i: PhysicsCmulation/physics/src/ForceObject.cpp.i

.PHONY : PhysicsCmulation/physics/src/ForceObject.i

# target to preprocess a source file
PhysicsCmulation/physics/src/ForceObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/ForceObject.cpp.i
.PHONY : PhysicsCmulation/physics/src/ForceObject.cpp.i

PhysicsCmulation/physics/src/ForceObject.s: PhysicsCmulation/physics/src/ForceObject.cpp.s

.PHONY : PhysicsCmulation/physics/src/ForceObject.s

# target to generate assembly for a file
PhysicsCmulation/physics/src/ForceObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/ForceObject.cpp.s
.PHONY : PhysicsCmulation/physics/src/ForceObject.cpp.s

PhysicsCmulation/physics/src/PhysicalObject.o: PhysicsCmulation/physics/src/PhysicalObject.cpp.o

.PHONY : PhysicsCmulation/physics/src/PhysicalObject.o

# target to build an object file
PhysicsCmulation/physics/src/PhysicalObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/PhysicalObject.cpp.o
.PHONY : PhysicsCmulation/physics/src/PhysicalObject.cpp.o

PhysicsCmulation/physics/src/PhysicalObject.i: PhysicsCmulation/physics/src/PhysicalObject.cpp.i

.PHONY : PhysicsCmulation/physics/src/PhysicalObject.i

# target to preprocess a source file
PhysicsCmulation/physics/src/PhysicalObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/PhysicalObject.cpp.i
.PHONY : PhysicsCmulation/physics/src/PhysicalObject.cpp.i

PhysicsCmulation/physics/src/PhysicalObject.s: PhysicsCmulation/physics/src/PhysicalObject.cpp.s

.PHONY : PhysicsCmulation/physics/src/PhysicalObject.s

# target to generate assembly for a file
PhysicsCmulation/physics/src/PhysicalObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/physics/src/PhysicalObject.cpp.s
.PHONY : PhysicsCmulation/physics/src/PhysicalObject.cpp.s

PhysicsCmulation/shapes/src/Point.o: PhysicsCmulation/shapes/src/Point.cpp.o

.PHONY : PhysicsCmulation/shapes/src/Point.o

# target to build an object file
PhysicsCmulation/shapes/src/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Point.cpp.o
.PHONY : PhysicsCmulation/shapes/src/Point.cpp.o

PhysicsCmulation/shapes/src/Point.i: PhysicsCmulation/shapes/src/Point.cpp.i

.PHONY : PhysicsCmulation/shapes/src/Point.i

# target to preprocess a source file
PhysicsCmulation/shapes/src/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Point.cpp.i
.PHONY : PhysicsCmulation/shapes/src/Point.cpp.i

PhysicsCmulation/shapes/src/Point.s: PhysicsCmulation/shapes/src/Point.cpp.s

.PHONY : PhysicsCmulation/shapes/src/Point.s

# target to generate assembly for a file
PhysicsCmulation/shapes/src/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Point.cpp.s
.PHONY : PhysicsCmulation/shapes/src/Point.cpp.s

PhysicsCmulation/shapes/src/Polygon.o: PhysicsCmulation/shapes/src/Polygon.cpp.o

.PHONY : PhysicsCmulation/shapes/src/Polygon.o

# target to build an object file
PhysicsCmulation/shapes/src/Polygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Polygon.cpp.o
.PHONY : PhysicsCmulation/shapes/src/Polygon.cpp.o

PhysicsCmulation/shapes/src/Polygon.i: PhysicsCmulation/shapes/src/Polygon.cpp.i

.PHONY : PhysicsCmulation/shapes/src/Polygon.i

# target to preprocess a source file
PhysicsCmulation/shapes/src/Polygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Polygon.cpp.i
.PHONY : PhysicsCmulation/shapes/src/Polygon.cpp.i

PhysicsCmulation/shapes/src/Polygon.s: PhysicsCmulation/shapes/src/Polygon.cpp.s

.PHONY : PhysicsCmulation/shapes/src/Polygon.s

# target to generate assembly for a file
PhysicsCmulation/shapes/src/Polygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Polygon.cpp.s
.PHONY : PhysicsCmulation/shapes/src/Polygon.cpp.s

PhysicsCmulation/shapes/src/Triangle.o: PhysicsCmulation/shapes/src/Triangle.cpp.o

.PHONY : PhysicsCmulation/shapes/src/Triangle.o

# target to build an object file
PhysicsCmulation/shapes/src/Triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Triangle.cpp.o
.PHONY : PhysicsCmulation/shapes/src/Triangle.cpp.o

PhysicsCmulation/shapes/src/Triangle.i: PhysicsCmulation/shapes/src/Triangle.cpp.i

.PHONY : PhysicsCmulation/shapes/src/Triangle.i

# target to preprocess a source file
PhysicsCmulation/shapes/src/Triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Triangle.cpp.i
.PHONY : PhysicsCmulation/shapes/src/Triangle.cpp.i

PhysicsCmulation/shapes/src/Triangle.s: PhysicsCmulation/shapes/src/Triangle.cpp.s

.PHONY : PhysicsCmulation/shapes/src/Triangle.s

# target to generate assembly for a file
PhysicsCmulation/shapes/src/Triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/shapes/src/Triangle.cpp.s
.PHONY : PhysicsCmulation/shapes/src/Triangle.cpp.s

PhysicsCmulation/src/Person.o: PhysicsCmulation/src/Person.cpp.o

.PHONY : PhysicsCmulation/src/Person.o

# target to build an object file
PhysicsCmulation/src/Person.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/src/Person.cpp.o
.PHONY : PhysicsCmulation/src/Person.cpp.o

PhysicsCmulation/src/Person.i: PhysicsCmulation/src/Person.cpp.i

.PHONY : PhysicsCmulation/src/Person.i

# target to preprocess a source file
PhysicsCmulation/src/Person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/src/Person.cpp.i
.PHONY : PhysicsCmulation/src/Person.cpp.i

PhysicsCmulation/src/Person.s: PhysicsCmulation/src/Person.cpp.s

.PHONY : PhysicsCmulation/src/Person.s

# target to generate assembly for a file
PhysicsCmulation/src/Person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/PhysicsCmulation/src/Person.cpp.s
.PHONY : PhysicsCmulation/src/Person.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysXCmulation.exe.dir/build.make CMakeFiles/PhysXCmulation.exe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PhysXCmulation.exe"
	@echo "... PhysicsCmulation/physics/src/ForceObject.o"
	@echo "... PhysicsCmulation/physics/src/ForceObject.i"
	@echo "... PhysicsCmulation/physics/src/ForceObject.s"
	@echo "... PhysicsCmulation/physics/src/PhysicalObject.o"
	@echo "... PhysicsCmulation/physics/src/PhysicalObject.i"
	@echo "... PhysicsCmulation/physics/src/PhysicalObject.s"
	@echo "... PhysicsCmulation/shapes/src/Point.o"
	@echo "... PhysicsCmulation/shapes/src/Point.i"
	@echo "... PhysicsCmulation/shapes/src/Point.s"
	@echo "... PhysicsCmulation/shapes/src/Polygon.o"
	@echo "... PhysicsCmulation/shapes/src/Polygon.i"
	@echo "... PhysicsCmulation/shapes/src/Polygon.s"
	@echo "... PhysicsCmulation/shapes/src/Triangle.o"
	@echo "... PhysicsCmulation/shapes/src/Triangle.i"
	@echo "... PhysicsCmulation/shapes/src/Triangle.s"
	@echo "... PhysicsCmulation/src/Person.o"
	@echo "... PhysicsCmulation/src/Person.i"
	@echo "... PhysicsCmulation/src/Person.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

